-- Frozen schema for DB_VERSION 2.
-- Generated by tests/bin/dump-schema.php from the real MySQL, not hand-written.
-- {PREFIX} is substituted by SchemaTestCase::install_frozen_schema().
-- Do not edit: this describes a schema that shipped, so changing it rewrites history.

CREATE TABLE `{PREFIX}paycrypto_me_bitcoin_wallet_xpubkeys` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `xpub` varchar(191) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `network` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_xpub_network` (`xpub`,`network`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `{PREFIX}paycrypto_me_bitcoin_derivation_indexes` (
  `derivation_index` bigint unsigned NOT NULL,
  `wallet_xpubkeys_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`derivation_index`,`wallet_xpubkeys_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `{PREFIX}paycrypto_me_bitcoin_transactions_data` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `payment_address` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `derivation_index_id` bigint unsigned NOT NULL,
  `wallet_xpubkeys_id` bigint unsigned NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `{PREFIX}paycrypto_me_lightning_invoices` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `node_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `invoice_id` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `payment_request` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `amount_sats` bigint unsigned DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `status` varchar(30) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'New',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
